# Generated by NeuroVerse Release Manager
# Uses a Node.js 25 base image for modern TypeScript support
FROM node:22-slim

# Set working directory
WORKDIR /app

# Copy the entire project
COPY . .

# Build the npm package
WORKDIR /app/npm
RUN npm install
RUN npm run build

# Set back to app root
WORKDIR /app

# Environment defaults
ENV MCP_TRANSPORT=stdio
ENV SAFETY_STRICT_MODE=false

# Entry point for the MCP server
ENTRYPOINT ["node", "npm/dist/index.js"]
